# Generated by Django 4.2.17 on 2025-02-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
